name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:20 # Updated to match the Node.js version used in the steps
        ports:
          - 4200:4200
        options: >-
          --health-cmd="curl --fail http://localhost:4200 || exit 1"
          --health-interval=30s # Increased interval to allow more time for the server to start
          --health-timeout=10s
          --health-retries=10 # Increased retries for better resilience

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --force

      - name: Start server
        run: npm start &
      
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:4200

      - name: Run Playwright tests
        run: npx playwright test